version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: online_shop

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: online_shop

#  backend:
#    image: dke
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/online_shop
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_DATA_MONGODB_URI: mongodb://mongo:password@mongo:27017/online_shop

#  frontend:
#    build: ./frontend
#    ports:
#      - "4200:4200"
#    environment:
#      BACKEND_URL: http://backend:8080

volumes:
  postgres_data:
  mongo_data:
